#ifndef PUMP_STATES_H_  
#define PUMP_STATES_H_

typedef enum {P_UNKNOWN,PROT_T_TRIP,P_FLOW_PROT,P_UNDERVOLTAGE,PROT_T_RESET,P_DISABLED, P_SUSPENDED,P_DELAY,P_OFF,P_RESUMED,P_ON} T_pump_states;


#endif